import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Sidebar } from "./sidebar";
import { GlobalContextProvider } from "./context/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AIMZ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContextProvider>
          <div className="w-screen h-screen grid grid-cols-10">
            {<Sidebar />}
            {children}
          </div>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
